---
title: Covid-19 Deaths Prediction in USA
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, include = TRUE, verbose = FALSE)
```

Updated on `r format(Sys.Date(), format="%B-%d-%Y")`.
The predictions CSV files are available at the https://github.com/tahmid-usc/covidGP/tree/master/prediction/deaths

```{r, echo=FALSE}
library(dplyr)
library(lubridate)
library(readr)
library(optimx)
library(kernlab)
library(mvtnorm)
library(ggplot2)
source('code/functions.R')
options(scipen=5)

# Read covid data

covid_data <- function (State  = 'South Carolina') {
  covid <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
  if(State == "US"){
    # Total USA: transform date and deaths
    covid$date <- as.Date(covid$date)
    covid.total <- covid %>% group_by(date) %>% summarize(deaths = sum(deaths)) 
    covid <- covid.total}
  else{
    # Read data and transform date and deaths
    # change state name as desired
    print(State)
    covid$date <- as.Date(covid$date)
    covid <- covid %>% dplyr:::filter(state == State) 
    
  }
  
  return(covid)
}




covidGP <- function(State = "South Carolina") {
  # Read data and transform date and deaths
  # change state name as desired

  covid <- covid_data(State)
  mindate <- as.numeric(min(covid$date))
  covid <- covid %>% mutate(t = (as.numeric(date) - mindate)/100, y = deaths / max(deaths))
  
  #print('Data Loaded')
  #Estimate hyperparamters (multistarts) (works better)
  #theta <- Hyper(x = covid$t, y = covid$y)
  theta.ms <- Hyper.ms(x = covid$t, y = covid$y)
  theta.sort <- theta.ms[order(theta.ms$value),]
  theta <- theta.sort[1,1:7] #might change set of values if the best doesnt work well
  theta <- as.numeric(theta)
  
  #print('Hyperparameters estimated')
  #---------- If hyperparamters are okay then do final prediction
  
  datestar <- covid$date
  datestar <- c(datestar, seq.Date(from = max(datestar), by = "day", length.out = 90))
  tstar <- (as.numeric(datestar) - mindate)/100
  
  mu.pred <- mu(covid$t,a = theta[4], b0 = theta[5], b1 = theta[6], v = theta[7])
  mustar.pred <- mu(tstar,a = theta[4], b0 = theta[5], b1 = theta[6], v = theta[7])
  
  
  n <- length(covid$t)
  nx <- length(tstar)
  kx <- ker2(x = tstar, y = covid$t, l = theta[1], sigf = theta[2])
  kxx <- ker(x = tstar, l = theta[1], sigf = theta[2]) + theta[3]^2 * diag(nx)
  k <- ker(x = covid$t, l = theta[1], sigf = theta[2]) + theta[3]^2 * diag(n)
  kinv <- chol2inv(chol(k))
  posmu <- kx %*% (kinv %*% matrix(covid$y - mu.pred, ncol = 1))
  posmu <- mustar.pred + posmu
  
  
  possigma <- kxx - kx %*% (kinv %*% t(kx))
  #diag(possigma)[diag(sigma)<0] <- 0
  
  posmu <- posmu * max(covid$deaths)
  mustar.pred <- mustar.pred * max(covid$deaths)
  ll <- posmu - 1.96 * sqrt(diag(possigma)) * max(covid$deaths)
  ul <- posmu + 1.96 * sqrt(diag(possigma)) * max(covid$deaths)
  
  #print('Posterior distribution computed')
  
  preddt <- data.frame(pred_date = datestar, posterior_mean = posmu, parametric_fit = mustar.pred, lower = ll, upper = ul)
  write.csv(preddt, file = paste0('prediction/deaths/', State, '.csv'), row.names = F)
  save(theta.sort, file = paste0('data/deaths/', 'theta_', State, '.Rdata'))
  
  
  #plot predictions
  maxVal <- round(theta[4] * max(covid$deaths),0)
#  print(paste("Upper asymptote = ", maxVal))
  ggplot(data = preddt, aes(x = pred_date, y = posterior_mean)) +
  geom_line(aes(x = pred_date, y = parametric_fit, colour = "Parametric Fit"), size = 1.2) +
  geom_smooth(aes(ymin = lower, ymax = upper), stat = "identity", fill = "skyblue") +   
  geom_line(size = 1.2, aes( colour = "Posterior Mean"), alpha = .9) +
  scale_y_continuous(n.breaks = 20) +
  scale_x_date(date_breaks = "2 week", date_labels = "%m-%d") +
  geom_point(data = covid, aes(x = date, y = deaths), colour = 1, shape = 1, size = 1.1) + 
  labs(x = "Date", y = "Total Deaths", colour = "") + ggtitle(paste('Cumulative COVID-19 Deaths Prediction for', State)) + 
  ggsave(filename = paste0('plot/deaths/', State, '.png'), height = 4, width = 12)
  
}

```


```{r, results='hide'}
covidGP("US")
```


```{r, results='hide'}
covidGP("Alabama")
```

```{r, results='hide'}
covidGP("Alaska")
```

```{r, results='hide'}
covidGP("Arizona")
```

```{r, results='hide'}
covidGP("Arkansas")
```

```{r, results='hide'}
covidGP("California")
```

```{r, results='hide'}
covidGP("Colorado")
```

```{r, results='hide'}
covidGP("Connecticut")
```

```{r, results='hide'}
covidGP("Delaware")
```

```{r, results='hide'}
covidGP("District of Columbia")
```

```{r, results='hide'}
covidGP("Florida")
```

```{r, results='hide'}
covidGP("Georgia")
```

```{r, results='hide'}
covidGP("Hawaii")
```

```{r, results='hide'}
covidGP("Idaho")
```

```{r, results='hide'}
covidGP("Illinois")
```

```{r, results='hide'}
covidGP("Indiana")
```

```{r, results='hide'}
covidGP("Iowa")
```

```{r, results='hide'}
covidGP("Kansas")
```

```{r, results='hide'}
covidGP("Kentucky")
```

```{r, results='hide'}
covidGP("Louisiana")
```

```{r, results='hide'}
covidGP("Maine")
```

```{r, results='hide'}
covidGP("Maryland")
```

```{r, results='hide'}
covidGP("Massachusetts")
```

```{r, results='hide'}
covidGP("Michigan")
```

```{r, results='hide'}
covidGP("Minnesota")
```

```{r, results='hide'}
covidGP("Mississippi")
```

```{r, results='hide'}
covidGP("Missouri")
```

```{r, results='hide'}
covidGP("Montana")
```

```{r, results='hide'}
covidGP("Nebraska")
```

```{r, results='hide'}
covidGP("Nevada")
```

```{r, results='hide'}
covidGP("New Hampshire")
```

```{r, results='hide'}
covidGP("New Jersey")
```

```{r, results='hide'}
covidGP("New Mexico")
```

```{r, results='hide'}
covidGP("New York")
```

```{r, results='hide'}
covidGP("North Carolina")
```

```{r, results='hide'}
covidGP("North Dakota")
```

```{r, results='hide'}
covidGP("Ohio")
```

```{r, results='hide'}
covidGP("Oklahoma")
```

```{r, results='hide'}
covidGP("Oregon")
```

```{r, results='hide'}
covidGP("Pennsylvania")
```

```{r, results='hide'}
covidGP("Rhode Island")
```

```{r, results='hide'}
covidGP("South Carolina")
```

```{r, results='hide'}
covidGP("South Dakota")
```

```{r, results='hide'}
covidGP("Tennessee")
```

```{r, results='hide'}
covidGP("Texas")
```

```{r, results='hide'}
covidGP("Utah")
```

```{r, results='hide'}
covidGP("Vermont")
```

```{r, results='hide'}
covidGP("Virginia")
```

```{r, results='hide'}
covidGP("Washington")
```

```{r, results='hide'}
covidGP("West Virginia")
```

```{r, results='hide'}
covidGP("Wisconsin")
```

```{r, results='hide'}
covidGP("Wyoming")
```
