---
title: Covid-19 Case Prediction Using Gaussian Process Regression with Richard's
  Growth Curve Prior
author: "Tahmidul Islam"
date: "5/8/2020"
output: html_document
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, include = TRUE, verbose = FALSE)
```

The numerical predictions are available in the [Github website] (https://github.com/tahmid-usc/covidGP/tree/master/docs/prediction)  

```{r, echo=FALSE}
#prior mean function (Richards growth equation)
mu <- function(t, a = 1, b0 = 1, b1 = 1, v = 1) {
  a / (1 + v * exp(- b1 * (t - b0)))^(1/v)
}

# RBF kernel

ker <- function(x, l, sigf) {
  rbf <- rbfdot(sigma = abs(l))
  return(abs(sigf) * kernelMatrix(rbf, x = x))
}

ker2 <- function(x, y, l, sigf) {
  rbf <- rbfdot(sigma = abs(l))
  return(abs(sigf) * kernelMatrix(rbf, x = x, y = y))
}


# Read covid data

covid_data <- function (State  = 'South Carolina') {
  covid <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
  if(State == "US"){
    # Total USA: transform date and cases
    covid$date <- as.Date(covid$date)
    covid.total <- covid %>% group_by(date) %>% summarize(cases = sum(cases)) 
    covid <- covid.total}
  else{
    # Read data and transform date and cases
    # change state name as desired
    print(State)
    covid$date <- as.Date(covid$date)
    covid <- covid %>% dplyr:::filter(state == State) 
    
  }
  
  return(covid)
}




#--- Multistart
#parseq <- c(.01,.1,1)
#parmat <- expand.grid(parseq, parseq, parseq, parseq, parseq, parseq, parseq)

parmat <-  matrix(rexp(105, 1), ncol = 7)

Hyper.ms <- function(x, y) {
  
  marlik <- function(theta) {
    x <- as.matrix(x)
    n <- dim(x)[1]
    #theta <- theta^2
    k <- ker(x = x, l = theta[1], sigf = theta[2])
    -dmvnorm(x = y, mean = mu(x, a = theta[4], b0 = theta[5], b1 = theta[6], v= theta[7]),  sigma = k + theta[3]^2 * diag(n), log = T)
  }
  
  hyp <- multistart(parmat=parmat, fn = marlik, method = 'Nelder-Mead',
                    control=list(maxit = 500000, trace = 0))
  #print(hyp)
  return(hyp)
  
}



```

```{r, echo=FALSE}
library(dplyr)
library(lubridate)
library(readr)
library(optimx)
library(kernlab)
library(mvtnorm)

covidGP <- function(State = "South Carolina") {
  # Read data and transform date and cases
  # change state name as desired
  
  #covid <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
  #covid$date <- as.Date(covid$date)
  covid <- covid_data(State)
  mindate <- as.numeric(min(covid$date))
  covid <- covid %>% mutate(t = (as.numeric(date) - mindate)/100, y = cases / max(cases))
  
  #print('Data Loaded')
  #Estimate hyperparamters (multistarts) (works better)
  #theta <- Hyper(x = covid$t, y = covid$y)
  theta.ms <- Hyper.ms(x = covid$t, y = covid$y)
  theta.sort <- theta.ms[order(theta.ms$value),]
  theta <- theta.sort[1,1:7] #might change set of values if the best doesnt work well
  theta <- as.numeric(theta)
  
  #print('Hyperparameters estimated')
  #---------- If hyperparamters are okay then do final prediction
  

datestar <- covid$date
datestar <- c(datestar, seq.Date(from = max(datestar), by = "day", length.out = 90))
tstar <- (as.numeric(datestar) - mindate)/100

mu.pred <- mu(covid$t,a = theta[4], b0 = theta[5], b1 = theta[6], v= theta[7])
mustar.pred <- mu(tstar,a = theta[4], b0 = theta[5], b1 = theta[6], v= theta[7])


n <- length(covid$t)
nx <- length(tstar)
kx <- ker2(x = tstar, y = covid$t, l = theta[1], sigf = theta[2])
kxx <- ker(x = tstar, l = theta[1], sigf = theta[2]) + theta[3]^2 * diag(nx)
k <- ker(x = covid$t, l = theta[1], sigf = theta[2]) + theta[3]^2 * diag(n)
kinv <- chol2inv(chol(k))
posmu <- kx %*% (kinv %*% matrix(covid$y - mu.pred, ncol = 1))
posmu <- mustar.pred + posmu


possigma <- kxx - kx %*% (kinv %*% t(kx))
diag(possigma)[diag(possigma)<0] <- 0
diag(possigma)[diag(possigma) == Inf] <- 1000000


posmu <- posmu * max(covid$cases)
mustar.pred <- mustar.pred * max(covid$cases)
ll <- posmu - 1.96 * sqrt(diag(possigma)) * max(covid$cases)
ul <- posmu + 1.96 * sqrt(diag(possigma)) * max(covid$cases)

  

  #plot predictions
  plot(datestar, posmu, lwd = 3, type = 'l', col = 2, main = paste('Cumulative COVID-19 cases Prediction for', State), xaxt = 'n', ylim = c(0, max(ul)), xlab = "Day", ylab = 'Cumulative cases')
  polygon(c(datestar,rev(datestar)),c(ll,rev(ul)),col=rgb (.1,.1,.1,.2),border=NA, xaxt = 'n')
  lines(datestar, posmu, lwd = 3, col = 2, xaxt = 'n')
  axis.Date(x = datestar, side = 1, format = '%m-%d', at = datestar)
  points(covid$date, covid$y * max(covid$cases), cex = 1.2)
  lines(datestar, mustar.pred, lwd = 3)
  legend('bottomright', c('Parametric fit', 'Posterior Mean'), lty = 1, 
         lwd = 3, col = 1:2, bty = 'n')
  
  preddt <- data.frame(pred_date = datestar, posterior_mean = posmu, parametric_fit = mustar.pred, lower = ll, upper = ul)
#  write.csv(preddt, file = paste0('prediction/', State, '.csv'), row.names = F)
#  save(theta.sort, file = paste0('prediction/', 'theta_', State, '.Rdata'))



}

```


```{r, results='hide'}
covidGP("US")
```


```{r, results='hide'}
covidGP("Alabama")
```

```{r, results='hide'}
covidGP("Alaska")
```
```{r, results='hide'}
covidGP("Arizona")
```

```{r, results='hide'}
covidGP("California")
```

```{r, results='hide'}
covidGP("Colorado")
```

```{r, results='hide'}
covidGP("Connecticut")
```

```{r, results='hide'}
covidGP("Delaware")
```

```{r, results='hide'}
covidGP("District of Columbia")
```

```{r, results='hide'}
covidGP("Florida")
```

```{r, results='hide'}
covidGP("Georgia")
```

```{r, results='hide'}
covidGP("Hawaii")
```

```{r, results='hide'}
covidGP("Idaho")
```

```{r, results='hide'}
covidGP("Illinois")
```

```{r, results='hide'}
covidGP("Indiana")
```

```{r, results='hide'}
covidGP("Iowa")
```

```{r, results='hide'}
covidGP("Kansas")
```

```{r, results='hide'}
covidGP("Kentucky")
```

```{r, results='hide'}
covidGP("Louisiana")
```

```{r, results='hide'}
covidGP("Maine")
```

```{r, results='hide'}
covidGP("Maryland")
```

```{r, results='hide'}
covidGP("Massachusetts")
```

```{r, results='hide'}
covidGP("Michigan")
```

```{r, results='hide'}
covidGP("South Carolina")
```

```{r, results='hide'}
covidGP("Minnesota")
```

```{r, results='hide'}
covidGP("Mississippi")
```

```{r, results='hide'}
covidGP("Missouri")
```

```{r, results='hide'}
covidGP("Montana")
```

```{r, results='hide'}
covidGP("Nebraska")
```

```{r, results='hide'}
covidGP("Nevada")
```

```{r, results='hide'}
covidGP("New Hampshire")
```

```{r, results='hide'}
covidGP("Ohio")
```

```{r, results='hide'}
covidGP("Oklahoma")
```

```{r, results='hide'}
covidGP("Oregon")
```

```{r, results='hide'}
covidGP("Pennsylvania")
```

```{r, results='hide'}
covidGP("Rhode Island")
```

```{r, results='hide'}
covidGP("South Carolina")
```

```{r, results='hide'}
covidGP("South Dakota")
```

```{r, results='hide'}
covidGP("Tennessee")
```

```{r, results='hide'}
covidGP("Texas")
```

```{r, results='hide'}
covidGP("Utah")
```

```{r, results='hide'}
covidGP("Vermont")
```

```{r, results='hide'}
covidGP("Virginia")
```

```{r, results='hide'}
covidGP("Washington")
```

```{r, results='hide'}
covidGP("West Virginia")
```

```{r, results='hide'}
covidGP("Wisconsin")
```

```{r, results='hide'}
covidGP("Wyoming")
```
